In [16]:
#These examples are taken from a book python for data science by 
import numpy as np
np.__version__

'1.16.2'

In [5]:
#creating array from python list

In [6]:
np.array([1,3,3,4])

array([1, 3, 3, 4])

In [7]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [22]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.full((2,2), 2.3)

array([[2.3, 2.3],
       [2.3, 2.3]])

In [25]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.arange(0,1,10)

array([0])

In [28]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [29]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [30]:
#create a 3*3 array of uniformly distributed random values between 0 and 1

In [31]:
np.random.random((3,3))

array([[0.34816215, 0.69841588, 0.36626684],
       [0.89536932, 0.05204063, 0.09104238],
       [0.81385068, 0.80328993, 0.41898381]])

In [33]:
#create a 3*3 array of normal distribution with mean = 0 and std=1
np.random.normal(0,1,(3,3))

array([[ 0.551876  ,  0.6650073 , -0.25613322],
       [-0.19728176, -0.617928  ,  0.77645744],
       [ 0.94979834, -2.72545615,  0.847005  ]])

In [34]:
np.random.randint(0,10,(3,3))

array([[3, 5, 5],
       [1, 6, 6],
       [2, 1, 3]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.empty(3)

array([1., 1., 1.])

In [8]:
#the basics of numpy array

In [10]:
#we use seed function to ensure that the same random number(array) generated each time when our code run

In [15]:
np.random.seed(0)
x1 = np.random.randint(10, size=6) #this is a one dimensional array containing 6 elements in range of 10
x2 = np.random.randint(10, size=(3,4)) # a 3*4 array (2 dimensional array)
x3 = np.random.randint(10, size=(3, 4, 5)) # a 3*4*5 array(a 3 dimensional array)

In [27]:
print("X2 ...The number of dimensions: {0} \n The size of each dimensions are : {1} The total size of the array is : {2}".format(x2.ndim, x2.shape, x2.size))

X2 ...The number of dimensions: 2 
 The size of each dimensions are : (3, 4) The total size of the array is : 12


In [33]:
'''
ndim--> is is a numpy ndarray attribute which tell us how many dimensions have the array contains
shape--> is is a numpy ndarray attribute which tell us what is the size of each dimensions
size--> is is a numpy ndarray attribute which tell us the total number of elements in the array
dtype--> is is a numpy ndarray attribute which tell us the data type of the array(since numpy not like python's list
        the elements in the array must be the same data type)
itemsize--> is is a numpy ndarray attribute which tell us the the size in byte of each array element
nbyte--> is is a numpy ndarray attribute which lists the total size (in bytes) of the array
'''

"\nndim--> is is a numpy ndarray attribute which tell us how many dimensions have the array contains\nshape--> is is a numpy ndarray attribute which tell us what is the size of each dimensions\nsize--> is is a numpy ndarray attribute which tell us the total number of elements in the array\ndtype--> is is a numpy ndarray attribute which tell us the data type of the array(since numpy not like python's list\n        the elements in the array must be the same data type)\nitemsize--> is is a numpy ndarray attribute which tell us the the size in byte of each array element\nnbyte--> is is a numpy ndarray attribute which lists the total size (in bytes) of the array\n"

In [32]:
print('dtype :', x2.dtype)

dtype : int64


In [35]:
print('each item in the array contains ', x2.itemsize, 'bytes')

each item in the array contains  8 bytes


In [37]:
print('the total byte the array contain ', x2.nbytes) # 3*4*8 = 96 (itemsize * size)

the total byte the array contain  96


In [39]:
#array indexing getting a single element
x1

array([5, 0, 3, 3, 7, 9])

In [40]:
x1[0]

5

In [41]:
x1[1]

0

In [42]:
#numpy array indexing is similar to python list indexing 
x1[-1] #to get the last element

9

In [45]:
#In multidimensional array you access the items using a comma separated tuple of indices

x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [46]:
x2[0,0]

3

In [50]:
#as we can see it like to get the elements in matrices the first value is the row and the second is the column
#to get the 3rd row and 3rd column element numpy array start indexing from zero dont forgot this
x2[2,2]

7

In [51]:
x1

array([5, 0, 3, 3, 7, 9])

In [52]:
x1[0] = 3.1414141 # to change the first element

In [53]:
x1

array([3, 0, 3, 3, 7, 9])

In [54]:
#since numpy arrays are fixed types if we try to change the element from int to float as the above example
#the value is store truncated it may be cause a lot of problems be aware of this

In [55]:
#Array slicing getting subarry
'''
 : is slicing notation 
 x[start:stop:step]
 if any of these are unspecified, they default value is start = 0, stop = size of dimensions step =1 
'''

'\n : is slicing notation \n x[start:stop:step]\n if any of these are unspecified, they default value is start = 0, stop = size of dimensions step =1 \n'

In [58]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
x[:5] # the first 5 elements

array([0, 1, 2, 3, 4])

In [61]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [62]:
x[2:5] #elements between index 2 to 5

array([2, 3, 4])

In [63]:
x[::2] #now the step value is 2 and start and stop are their default value (0 and size of dimensions)

array([0, 2, 4, 6, 8])

In [64]:
x[1::2] #start=1, stop=default, step=2

array([1, 3, 5, 7, 9])

In [66]:
x[::-1] 
#if the step value is negative number the start and stop value is swapped 

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [72]:
x[5::-2]


array([5, 3, 1])

In [73]:
#multidimensional subarray
'''
it works with multiple slices separated by commas
'''

'\nit works with multiple slices separated by commas\n'

In [74]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [76]:
x2.ndim

2

In [77]:
x2.shape

(3, 4)

In [80]:
x2[:2, :3] # two rows, and three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [81]:
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [85]:
x2[::-1, ::-1] # to reverse the array with all dimensions

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [86]:
x2[::-1,::] #to reverse rows

array([[1, 6, 7, 7],
       [7, 6, 8, 8],
       [3, 5, 2, 4]])

In [87]:
x2[::,::-1] #to reverse columns

array([[4, 2, 5, 3],
       [8, 8, 6, 7],
       [7, 7, 6, 1]])

In [95]:
#Accessing array rows and columns
'''
you can do this by combingin indexing and slicing, using an empty slice marked by single colon
in case row access, the empty slice can be ommited for more compact syntax
'''

'\nyou can do this by combingin indexing and slicing, using an empty slice marked by single colon\nin case row access, the empty slice can be ommited for more compact syntax\n'

In [89]:
x2[:, 0] #to get the first columns of the array

array([3, 7, 1])

In [91]:
x2[0, :] #to get the first row of the array

array([3, 5, 2, 4])

In [96]:
x2[0] #omit the second empty slice colon x2[0,:]

array([3, 5, 2, 4])

In [97]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [101]:
x2[:2:,:2]

array([[3, 5],
       [7, 6]])

In [102]:
x2_sub = x2[:2, :2]

In [103]:
x2_sub

array([[3, 5],
       [7, 6]])

In [104]:
x2_sub[0,0] = 99

In [105]:
x2_sub

array([[99,  5],
       [ 7,  6]])

In [106]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [107]:
#as we can see if we modify the subarray the original array also changed this is because array slicing in numpy
#will return the view of the array not the copy of it

In [111]:
#if we dont want the change in the subarray not modify the original array we can use the copy function

x2_sub = x2[:2,:2].copy()
print("initial value \n", x2_sub)
x2_sub[0,0] = 42
print("after change \n ", x2_sub)
print("original array \n", x2)

initial value 
 [[99  5]
 [ 7  6]]
after change 
  [[42  5]
 [ 7  6]]
original array 
 [[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [112]:
#as we can see the original array not altered if we use the copy method when we slice an array

In [113]:
#Reshaping of array

In [114]:
grid = np.arange(1,10).reshape(3,3)

In [115]:
grid.shape

(3, 3)

In [116]:
grid.ndim

2

In [117]:
grid.size

9

In [118]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
#for the reshape to work the size of initial array must match the size of the reshaped array

In [120]:
x = np.array([1,2,3])

In [121]:
x.reshape((1,3))

array([[1, 2, 3]])

In [122]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [123]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [124]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [125]:
#Array concatenation and splitting

In [126]:
'''
to concatenate multiple array we can use
1)np.concatenate
2)np.vstack  --> vertical stack
3)np.hstack  --> horizontal stack
'''

'\nto concatenate multiple array we can use\n1)np.concatenate\n2)np.vstack\n3)np.hstack\n'

In [128]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [129]:
z = np.array([99,99,99])
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  5,  6, 99, 99, 99])

In [131]:
#np.concatenate can be use to 2d 
grid = np.array([[1,2,3], 
                 [4,5,6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [132]:
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [133]:
np.concatenate([grid, grid], axis=1) #axis is zero indexing this concatenate along the second axis

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [134]:
#when working with arrays of mixed dimensions it can be clear to use np.vstack and np.hstack

In [140]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                [6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [141]:
#when working with np.vstack and np.hstack all the input arrays must have same number of dimensions

In [143]:
y = np.array([[99],
             [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [144]:
#np.dstack will stack arrays along the third axis

In [147]:
third_dim = np.dstack([grid, grid]) 

In [148]:
third_dim.shape

(2, 3, 2)

In [149]:
third_dim

array([[[9, 9],
        [8, 8],
        [7, 7]],

       [[6, 6],
        [5, 5],
        [4, 4]]])

In [150]:
#splitting of arrays

In [151]:
'''
to split an array we can use
1)np.split
2)np.hsplit
3)np.vsplit
'''

'\nto split an array we can use\n1)np.split\n2)np.hsplit\n3)np.vsplit\n'

In [152]:
x =[1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])

In [153]:
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [154]:
#N split points lead to N+1 subarrays

In [155]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [156]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [158]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [159]:
#np.dsplit split array along the third axis

In [160]:
#Computation no NumPy Array: Universal function