In [1]:
import numpy as np
np.__version__

'1.16.2'

In [5]:
#creating array from python list

In [6]:
np.array([1,3,3,4])

array([1, 3, 3, 4])

In [7]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [22]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.full((2,2), 2.3)

array([[2.3, 2.3],
       [2.3, 2.3]])

In [25]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.arange(0,1,10)

array([0])

In [28]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [29]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [30]:
#create a 3*3 array of uniformly distributed random values between 0 and 1

In [31]:
np.random.random((3,3))

array([[0.34816215, 0.69841588, 0.36626684],
       [0.89536932, 0.05204063, 0.09104238],
       [0.81385068, 0.80328993, 0.41898381]])

In [33]:
#create a 3*3 array of normal distribution with mean = 0 and std=1
np.random.normal(0,1,(3,3))

array([[ 0.551876  ,  0.6650073 , -0.25613322],
       [-0.19728176, -0.617928  ,  0.77645744],
       [ 0.94979834, -2.72545615,  0.847005  ]])

In [34]:
np.random.randint(0,10,(3,3))

array([[3, 5, 5],
       [1, 6, 6],
       [2, 1, 3]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.empty(3)

array([1., 1., 1.])

In [8]:
#the basics of numpy array

In [ ]:
#we use seed function to ensure that t