In [1]:
#These examples are taken from a book python for data science by 
import numpy as np
np.__version__

'1.16.2'

In [2]:
#creating array from python list

In [3]:
np.array([1,3,3,4])

array([1, 3, 3, 4])

In [4]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.full((2,2), 2.3)

array([[2.3, 2.3],
       [2.3, 2.3]])

In [8]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.arange(0,1,10)

array([0])

In [10]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [11]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [12]:
#create a 3*3 array of uniformly distributed random values between 0 and 1

In [13]:
np.random.random((3,3))

array([[0.93165015, 0.10346664, 0.55826487],
       [0.28093631, 0.81213368, 0.09020641],
       [0.1352936 , 0.16144347, 0.83942737]])

In [14]:
#create a 3*3 array of normal distribution with mean = 0 and std=1
np.random.normal(0,1,(3,3))

array([[-0.0194434 , -0.96391821,  0.09335265],
       [-0.25019847, -0.98238091,  0.44744954],
       [ 2.14034242, -1.1191366 , -1.18715777]])

In [15]:
np.random.randint(0,10,(3,3))

array([[8, 2, 3],
       [2, 7, 9],
       [7, 4, 3]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.empty(3)

array([1., 1., 1.])

In [18]:
#the basics of numpy array

In [19]:
#we use seed function to ensure that the same random number(array) generated each time when our code run

In [20]:
np.random.seed(0)
x1 = np.random.randint(10, size=6) #this is a one dimensional array containing 6 elements in range of 10
x2 = np.random.randint(10, size=(3,4)) # a 3*4 array (2 dimensional array)
x3 = np.random.randint(10, size=(3, 4, 5)) # a 3*4*5 array(a 3 dimensional array)

In [21]:
print("X2 ...The number of dimensions: {0} \n The size of each dimensions are : {1} The total size of the array is : {2}".format(x2.ndim, x2.shape, x2.size))

X2 ...The number of dimensions: 2 
 The size of each dimensions are : (3, 4) The total size of the array is : 12


In [22]:
'''
ndim--> is is a numpy ndarray attribute which tell us how many dimensions have the array contains
shape--> is is a numpy ndarray attribute which tell us what is the size of each dimensions
size--> is is a numpy ndarray attribute which tell us the total number of elements in the array
dtype--> is is a numpy ndarray attribute which tell us the data type of the array(since numpy not like python's list
        the elements in the array must be the same data type)
itemsize--> is is a numpy ndarray attribute which tell us the the size in byte of each array element
nbyte--> is is a numpy ndarray attribute which lists the total size (in bytes) of the array
'''

"\nndim--> is is a numpy ndarray attribute which tell us how many dimensions have the array contains\nshape--> is is a numpy ndarray attribute which tell us what is the size of each dimensions\nsize--> is is a numpy ndarray attribute which tell us the total number of elements in the array\ndtype--> is is a numpy ndarray attribute which tell us the data type of the array(since numpy not like python's list\n        the elements in the array must be the same data type)\nitemsize--> is is a numpy ndarray attribute which tell us the the size in byte of each array element\nnbyte--> is is a numpy ndarray attribute which lists the total size (in bytes) of the array\n"

In [23]:
print('dtype :', x2.dtype)

dtype : int64


In [24]:
print('each item in the array contains ', x2.itemsize, 'bytes')

each item in the array contains  8 bytes


In [25]:
print('the total byte the array contain ', x2.nbytes) # 3*4*8 = 96 (itemsize * size)

the total byte the array contain  96


In [26]:
#array indexing getting a single element
x1

array([5, 0, 3, 3, 7, 9])

In [27]:
x1[0]

5

In [28]:
x1[1]

0

In [29]:
#numpy array indexing is similar to python list indexing 
x1[-1] #to get the last element

9

In [30]:
#In multidimensional array you access the items using a comma separated tuple of indices

x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [31]:
x2[0,0]

3

In [32]:
#as we can see it like to get the elements in matrices the first value is the row and the second is the column
#to get the 3rd row and 3rd column element numpy array start indexing from zero dont forgot this
x2[2,2]

7

In [33]:
x1

array([5, 0, 3, 3, 7, 9])

In [34]:
x1[0] = 3.1414141 # to change the first element

In [35]:
x1

array([3, 0, 3, 3, 7, 9])

In [36]:
#since numpy arrays are fixed types if we try to change the element from int to float as the above example
#the value is store truncated it may be cause a lot of problems be aware of this

In [37]:
#Array slicing getting subarry
'''
 : is slicing notation 
 x[start:stop:step]
 if any of these are unspecified, they default value is start = 0, stop = size of dimensions step =1 
'''

'\n : is slicing notation \n x[start:stop:step]\n if any of these are unspecified, they default value is start = 0, stop = size of dimensions step =1 \n'

In [38]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
x[:5] # the first 5 elements

array([0, 1, 2, 3, 4])

In [40]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [41]:
x[2:5] #elements between index 2 to 5

array([2, 3, 4])

In [42]:
x[::2] #now the step value is 2 and start and stop are their default value (0 and size of dimensions)

array([0, 2, 4, 6, 8])

In [43]:
x[1::2] #start=1, stop=default, step=2

array([1, 3, 5, 7, 9])

In [44]:
x[::-1] 
#if the step value is negative number the start and stop value is swapped 

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [45]:
x[5::-2]


array([5, 3, 1])

In [46]:
#multidimensional subarray
'''
it works with multiple slices separated by commas
'''

'\nit works with multiple slices separated by commas\n'

In [47]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [48]:
x2.ndim

2

In [49]:
x2.shape

(3, 4)

In [50]:
x2[:2, :3] # two rows, and three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [51]:
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [52]:
x2[::-1, ::-1] # to reverse the array with all dimensions

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [53]:
x2[::-1,::] #to reverse rows

array([[1, 6, 7, 7],
       [7, 6, 8, 8],
       [3, 5, 2, 4]])

In [54]:
x2[::,::-1] #to reverse columns

array([[4, 2, 5, 3],
       [8, 8, 6, 7],
       [7, 7, 6, 1]])

In [55]:
#Accessing array rows and columns
'''
you can do this by combingin indexing and slicing, using an empty slice marked by single colon
in case row access, the empty slice can be ommited for more compact syntax
'''

'\nyou can do this by combingin indexing and slicing, using an empty slice marked by single colon\nin case row access, the empty slice can be ommited for more compact syntax\n'

In [56]:
x2[:, 0] #to get the first columns of the array

array([3, 7, 1])

In [57]:
x2[0, :] #to get the first row of the array

array([3, 5, 2, 4])

In [58]:
x2[0] #omit the second empty slice colon x2[0,:]

array([3, 5, 2, 4])

In [59]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [60]:
x2[:2:,:2]

array([[3, 5],
       [7, 6]])

In [61]:
x2_sub = x2[:2, :2]

In [62]:
x2_sub

array([[3, 5],
       [7, 6]])

In [63]:
x2_sub[0,0] = 99

In [64]:
x2_sub

array([[99,  5],
       [ 7,  6]])

In [65]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [66]:
#as we can see if we modify the subarray the original array also changed this is because array slicing in numpy
#will return the view of the array not the copy of it

In [67]:
#if we dont want the change in the subarray not modify the original array we can use the copy function

x2_sub = x2[:2,:2].copy()
print("initial value \n", x2_sub)
x2_sub[0,0] = 42
print("after change \n ", x2_sub)
print("original array \n", x2)

initial value 
 [[99  5]
 [ 7  6]]
after change 
  [[42  5]
 [ 7  6]]
original array 
 [[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [68]:
#as we can see the original array not altered if we use the copy method when we slice an array

In [69]:
#Reshaping of array

In [70]:
grid = np.arange(1,10).reshape(3,3)

In [71]:
grid.shape

(3, 3)

In [72]:
grid.ndim

2

In [73]:
grid.size

9

In [74]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
#for the reshape to work the size of initial array must match the size of the reshaped array

In [76]:
x = np.array([1,2,3])

In [77]:
x.reshape((1,3))

array([[1, 2, 3]])

In [78]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [79]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [80]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [81]:
#Array concatenation and splitting

In [82]:
'''
to concatenate multiple array we can use
1)np.concatenate
2)np.vstack  --> vertical stack
3)np.hstack  --> horizontal stack
'''

'\nto concatenate multiple array we can use\n1)np.concatenate\n2)np.vstack  --> vertical stack\n3)np.hstack  --> horizontal stack\n'

In [83]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [84]:
z = np.array([99,99,99])
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  5,  6, 99, 99, 99])

In [85]:
#np.concatenate can be use to 2d 
grid = np.array([[1,2,3], 
                 [4,5,6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [86]:
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [87]:
np.concatenate([grid, grid], axis=1) #axis is zero indexing this concatenate along the second axis

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [88]:
#when working with arrays of mixed dimensions it can be clear to use np.vstack and np.hstack

In [89]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                [6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [90]:
#when working with np.vstack and np.hstack all the input arrays must have same number of dimensions

In [91]:
y = np.array([[99],
             [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [92]:
#np.dstack will stack arrays along the third axis

In [93]:
third_dim = np.dstack([grid, grid]) 

In [94]:
third_dim.shape

(2, 3, 2)

In [95]:
third_dim

array([[[9, 9],
        [8, 8],
        [7, 7]],

       [[6, 6],
        [5, 5],
        [4, 4]]])

In [96]:
#splitting of arrays

In [97]:
'''
to split an array we can use
1)np.split
2)np.hsplit
3)np.vsplit
'''

'\nto split an array we can use\n1)np.split\n2)np.hsplit\n3)np.vsplit\n'

In [98]:
x =[1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])

In [99]:
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [100]:
#N split points lead to N+1 subarrays

In [101]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [102]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [103]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [104]:
#np.dsplit split array along the third axis

In [106]:
#Computation on NumPy Array: Universal function

In [107]:
#numpy provides an easy and flexible interface to optimized computation with arrays of data

In [108]:
np.random.seed(0)
def compute_reciprocals(value):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [120]:
#now lets compute the time this function take to finish execution
big_array = np.random.randint(1, 100, size=1000000)
%timeit (compute_reciprocals(big_array))

27.9 µs ± 292 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [115]:
'''
The reason why the above code is so slow because of the type checking and function dispatchs that the CPython
must do at each cycle of the loop

For many types of operations, Numpy provides a convenient interface into just this kind of statically typed, 
compiled routine. this is known as vectorized operation

This vectorized approach is designed to push the loop into the compiled layer that underlies NumPy, leading to 
much faster execution
'''

'\nThe reason why the above code is so slow because of the type checking and function dispatchs that the CPython\nmust do at each cycle of the loop\n\nFor many types of operations, Numpy provides a convenient interface into just this kind of statically typed, \ncompiled routine. this is known as vectorized operation\n\nThis vectorized approach is designed to push the loop into the compiled layer that underlies NumPy, leading to \nmuch faster execution\n'

In [118]:
print(compute_reciprocals(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [119]:
%timeit (1.0/big_array)

6.12 ms ± 39 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [121]:
'''
Vectorized operations in NumPy are implemented via ufuncs, whose main purpose is to quickly execute repeateed 
operations on values in NumPy array
'''

'\nVectorized operations in NumPy are implemented via ufuncs, whose main purpose is to quickly execute repeateed \noperations on values in NumPy array\n'

In [122]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [124]:
x = np.arange(9).reshape((3,3))

In [125]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
2**x #do vectorized implementation of 2 raise by each element power

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [127]:
#Vectorized implementation is always faster than explicit for loop implementation especially when the array is big

In [130]:
x = np.arange(4)
print("x is ", x)
print("x + 5 is ", x + 5)
print("x - 5 is ", x - 5)
print("x * 5 is ", x * 5)
print("x / 5 is ", x / 5)
print("x % 5 is ", x % 5)
print("x ** 2 is ", x ** 2)
print("-x is ", -x)

x is  [0 1 2 3]
x + 5 is  [5 6 7 8]
x - 5 is  [-5 -4 -3 -2]
x * 5 is  [ 0  5 10 15]
x / 5 is  [0.  0.2 0.4 0.6]
x % 5 is  [0 1 2 3]
x ** 2 is  [0 1 4 9]
-x is  [ 0 -1 -2 -3]


In [133]:
#stadard oreder of operations are respected in numpy ufunc implementation

-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [134]:
x 

array([0, 1, 2, 3])

In [135]:
x + 2

array([2, 3, 4, 5])

In [136]:
np.add(x,2) # is the same as x+2

array([2, 3, 4, 5])

In [138]:
'''
All the arithmetic operations are simply convenient wrappers around specific function built into NumPy
+ --> np.add -->           Addition (e.g., 1 + 1 = 2 )
- --> np.subtract -->      Subtraction (e.g., 3 - 2 = 1 )
- --> np.negative -->      Unary negation (e.g., -2 )
* --> np.multiply -->      Multiplication (e.g., 2 * 3 = 6 )
/ --> np.divide -->        Division (e.g., 3 / 2 = 1.5 )
// --> np.floor_divide --> Floor division (e.g., 3 // 2 = 1 )
** --> np.power -->        Exponentiation (e.g., 2 ** 3 = 8 )
% --> np.mod -->           Modulus/remainder (e.g., 9 % 4 = 1 )
'''

'\nAll the arithmetic operations are simply convenient wrappers around specific function built into NumPy\n+ --> np.add -->           Addition (e.g., 1 + 1 = 2 )\n- --> np.subtract -->      Subtraction (e.g., 3 - 2 = 1 )\n- --> np.negative -->      Unary negation (e.g., -2 )\n* --> np.multiply -->      Multiplication (e.g., 2 * 3 = 6 )\n/ --> np.divide -->        Division (e.g., 3 / 2 = 1.5 )\n// --> np.floor_divide --> Floor division (e.g., 3 // 2 = 1 )\n** --> np.power -->        Exponentiation (e.g., 2 ** 3 = 8 )\n% --> np.mod -->           Modulus/remainder (e.g., 9 % 4 = 1 )\n'

In [139]:
np.abs(x)

array([0, 1, 2, 3])

In [140]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])

In [141]:
x.dtype

dtype('complex128')

In [142]:
np.abs(x)

array([5., 5., 2., 1.])

In [150]:
#Trignometric function
theta = np.linspace(0, np.pi, 3)
print('theta = ', theta)
print('sin(theta) = ', np.sin(theta))
print('cos(theta) = ', np.cos(theta))
print('tan(theta) = ', np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [152]:
#computing inverse trignometric
theta = [-1, 0, 1]
print('theta = ', theta)
print('arcsin(theta) = ', np.arcsin(theta))
print('arccos(theta) = ', np.arccos(theta))
print('arctan(theta) = ', np.arctan(theta))

theta =  [-1, 0, 1]
arcsin(theta) =  [-1.57079633  0.          1.57079633]
arccos(theta) =  [3.14159265 1.57079633 0.        ]
arctan(theta) =  [-0.78539816  0.          0.78539816]


In [154]:
#Exponents and logarithms
#computing exponentials
x = [1, 2, 3]
print('x = ', x)
print('e ^ x = ', np.exp(x))
print('2 ^ x = ', np.exp2(x))
print('3 ^ x = ', np.power(3, x))

x =  [1, 2, 3]
e ^ x =  [ 2.71828183  7.3890561  20.08553692]
2 ^ x =  [2. 4. 8.]
3 ^ x =  [ 3  9 27]


In [155]:
#computing logarithms
x = [1, 2, 3, 4, 10]
print('x = ', x)
print('log(x) = ', np.log(x)) #natural logarithm
print('log2(x) = ', np.log2(x)) #base 2 logarithm  
print('log10(x) = ', np.log10(x)) #base 10 logarithm

x =  [1, 2, 3, 4, 10]
log(x) =  [0.         0.69314718 1.09861229 1.38629436 2.30258509]
log2(x) =  [0.         1.         1.5849625  2.         3.32192809]
log10(x) =  [0.         0.30103    0.47712125 0.60205999 1.        ]


In [160]:
#when our inputs are very small we can use spcialized function to maintain precision
x = [0, 0.001, 0.01, 0.1]
print('exp(x) - 1 = ', np.expm1(x))
print('log(x+1) = ', np.log1p(x))

exp(x) - 1 =  [0.         0.0010005  0.01005017 0.10517092]
log(x+1) =  [0.         0.0009995  0.00995033 0.09531018]


In [162]:
#specifying output
#it is useful to be able to specify the array where the result of the calculation will be stored
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)

array([ 0., 10., 20., 30., 40.])

In [163]:
y

array([ 0., 10., 20., 30., 40.])

In [164]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [167]:
#Aggregates
#A reduce repeatedly applies a given operation to the elements of an array until only a single result remains
x = np.arange(1, 6)
np.add.reduce(x)

15

In [168]:
np.multiply.reduce(x)

120

In [169]:
#if we'd like to store all the intermediate results of the computations, we can instead use accumulate
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [170]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [172]:
#outer function 
#any ufunc can computer the output of all pairs of two differnt inputs using the outer method

x = np.arange(1, 13) # to create a multiplication table 
np.multiply.outer(x, x)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]])

In [174]:
#Aggregation min, max and everything between 

In [175]:
#Summing the values in array
L = np.random.random(100)
sum(L)

49.00305769003354

In [176]:
np.sum(L)

49.00305769003355

In [177]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

137 ms ± 7.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.38 ms ± 66.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [178]:
#because it executes the operation in compiled code, Numpy's version of the operation is computed much faster

In [179]:
min(big_array), max(big_array)

(1.890489775835391e-07, 0.9999993031657582)

In [180]:
np.min(big_array), np.max(big_array)

(1.890489775835391e-07, 0.9999993031657582)

In [181]:
%timeit min(big_array)
%timeit np.min(big_array)

114 ms ± 2.98 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.37 ms ± 57.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [182]:
#for min, max, sum we can use this function on the ndarray object itself

print(big_array.sum(), big_array.min(), big_array.max())

499866.95938387926 1.890489775835391e-07 0.9999993031657582


In [183]:
#multidimensional aggregates
M = np.random.random((3, 4))
print(M)

[[0.79662618 0.90495136 0.40594038 0.66590549]
 [0.53870581 0.00508357 0.75203249 0.49609569]
 [0.02720774 0.3840409  0.71356615 0.00992866]]


In [185]:
#by default each numpy aggregate function will return the aggregate over the entire array
M.sum()

5.700084401013591

In [186]:
#Aggregation functions take an additional argument specifying the axis along which the aggregate is computed
#The axis keyword specifies the dimension of the array that will be collapsed
M.min(axis=0)

array([0.02720774, 0.00508357, 0.40594038, 0.00992866])

In [187]:
M.min(axis=1)

array([0.40594038, 0.00508357, 0.00992866])

In [189]:
'''
a NaN-safe counterpart computes the result while ignoring missing values 
 
Aggregate function in numpy

np.sum            np.nansum          Compute sum of elements
np.prod           np.nanprod         Compute product of elements
np.mean           np.nanmean         Compute median of elements
np.std            np.nanstd          Compute standard deviation
np.var            np.nanvar          Compute variance
np.min            np.nanmin          Find minimum value
np.max            np.nanmax          Find maximum value
np.argmin         np.nanargmin       Find index of minimum value
np.argmax         np.nanargmax       Find index of maximum value
np.median         np.nanmedian       Compute median of elements
np.percentile     np.nanpercentile   Compute rank-based statistics of elements
np.any            N/A Evaluate       whether any elements are true
np.all            N/A Evaluate       whether all elements are true

'''

'\na NaN-safe counterpart computes the result while ignoring missing values \n \nAggregate function in numpy\n\nnp.sum            np.nansum          Compute sum of elements\nnp.prod           np.nanprod         Compute product of elements\nnp.mean           np.nanmean         Compute median of elements\nnp.std            np.nanstd          Compute standard deviation\nnp.var            np.nanvar          Compute variance\nnp.min            np.nanmin          Find minimum value\nnp.max            np.nanmax          Find maximum value\nnp.argmin         np.nanargmin       Find index of minimum value\nnp.argmax         np.nanargmax       Find index of maximum value\nnp.median         np.nanmedian       Compute median of elements\nnp.percentile     np.nanpercentile   Compute rank-based statistics of elements\nnp.any            N/A Evaluate       whether any elements are true\nnp.all            N/A Evaluate       whether all elements are true\n\n'